// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRvXDKz-ZTrGHEYNQ3ameg6vFFO9TBBwE',
    appId: '1:819634197812:web:a1068ae7414a914e0c4161',
    messagingSenderId: '819634197812',
    projectId: 'uniconnect-a3831',
    authDomain: 'uniconnect-a3831.firebaseapp.com',
    storageBucket: 'uniconnect-a3831.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf9cB7bE8GGx9iauLAWgFxXA8_jrhacGA',
    appId: '1:819634197812:android:53fe8b43803815280c4161',
    messagingSenderId: '819634197812',
    projectId: 'uniconnect-a3831',
    storageBucket: 'uniconnect-a3831.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6eKzcEnYaO8KOQwScZJvDKYSwcsPVZxc',
    appId: '1:819634197812:ios:04bbde8a2d7c085d0c4161',
    messagingSenderId: '819634197812',
    projectId: 'uniconnect-a3831',
    storageBucket: 'uniconnect-a3831.firebasestorage.app',
    iosBundleId: 'com.example.uniConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6eKzcEnYaO8KOQwScZJvDKYSwcsPVZxc',
    appId: '1:819634197812:ios:04bbde8a2d7c085d0c4161',
    messagingSenderId: '819634197812',
    projectId: 'uniconnect-a3831',
    storageBucket: 'uniconnect-a3831.firebasestorage.app',
    iosBundleId: 'com.example.uniConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRvXDKz-ZTrGHEYNQ3ameg6vFFO9TBBwE',
    appId: '1:819634197812:web:71d464ff90383e070c4161',
    messagingSenderId: '819634197812',
    projectId: 'uniconnect-a3831',
    authDomain: 'uniconnect-a3831.firebaseapp.com',
    storageBucket: 'uniconnect-a3831.firebasestorage.app',
  );
}
